CREATE TABLE IF NOT EXISTS reports (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  at INTEGER NOT NULL,
  body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS probes (
  component TEXT PRIMARY KEY,
  at INTEGER NOT NULL,
  state TEXT NOT NULL,
  ms INTEGER,
  detail TEXT
);

CREATE TABLE IF NOT EXISTS daily (
  component TEXT NOT NULL,
  day TEXT NOT NULL,
  ok INTEGER NOT NULL DEFAULT 0,
  degraded INTEGER NOT NULL DEFAULT 0,
  down INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (component, day)
);

CREATE TABLE IF NOT EXISTS incidents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  impact TEXT NOT NULL,
  affects TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  resolved_at INTEGER
);

CREATE TABLE IF NOT EXISTS updates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  incident_id INTEGER NOT NULL REFERENCES incidents(id),
  at INTEGER NOT NULL,
  status TEXT NOT NULL,
  body TEXT NOT NULL
);
