name = "gronka-status"
main = "src/worker.js"
compatibility_date = "2026-09-01"
upload_source_maps = false
workers_dev = false
routes = [{ pattern = "status.gronka.dev", custom_domain = true }]

[assets]
directory = "public"
binding = "ASSETS"

[triggers]
crons = ["*/5 * * * *"]

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "gronka-status"
database_id = "ccf2cbfd-9762-46cd-9770-e61591b36713"
